#!/bin/bash

# ssh-agent
if [ -z "$SSH_AUTH_SOCK" ]; then
    RUNNING_AGENT="$(ps -ax | grep 'ssh-agent -s' | grep - grep | wc -l | tr -d '[:space:]')"
    if [ "$RUNNING_AGENT" = "0" ]; then
        ssh-agent -s &>$HOME/.local/state/ssh-agent
    fi
    eval $(cat $HOME/.local/state/ssh-agent)
fi

# zsh
[ -z "$PS1" ] && return

if [ -f "/home/linuxbrew/.linuxbrew/bin/zsh" ]; then
    ZSH="/home/linuxbrew/.linuxbrew/bin/zsh"
    [ -x "${ZSH}" ] && SHELL="${ZSH}" exec "${ZSH}" -l
    return

elif [ -f "${HOME}/.homebrew/bin/zsh" ]; then
    ZSH="${HOME}/.homebrew/bin/zsh"
    [ -x "${ZSH}" ] && SHELL="${ZSH}" exec "${ZSH}" -l
    return

elif [ -f "/usr/bin/zsh" ]; then
    ZSH="/usr/bin/zsh"
    [ -x "${ZSH}" ] && SHELL="${ZSH}" exec "${ZSH}" -l
    return
else
    echo "zsh not found"
fi
