#!/bin/bash

# ssh-agent
if [ -f $HOME/.local/state/ssh-agent ]; then
    . $HOME/.local/state/ssh-agent > /dev/null
fi
if [ -z "$SSH_AGENT_PID" ] || ! kill -0 $SSH_AGENT_PID; then
    ssh-agent > $HOME/.local/state/ssh-agent && . $HOME/.local/state/ssh-agent > /dev/null
fi

# zsh
[ -z "$PS1" ] && return

if [ -f "/home/linuxbrew/.linuxbrew/bin/zsh" ]; then
    ZSH="/home/linuxbrew/.linuxbrew/bin/zsh"
    [ -x "${ZSH}" ] && SHELL="${ZSH}" exec "${ZSH}" -l
    return

elif [ -f "${HOME}/.homebrew/bin/zsh" ]; then
    ZSH="${HOME}/.homebrew/bin/zsh"
    [ -x "${ZSH}" ] && SHELL="${ZSH}" exec "${ZSH}" -l
    return

elif [ -f "/usr/bin/zsh" ]; then
    ZSH="/usr/bin/zsh"
    [ -x "${ZSH}" ] && SHELL="${ZSH}" exec "${ZSH}" -l
    return
else
    echo "zsh not found"
fi

