#!/bin/zsh

# proxy
source $HOME/.ssh/bin/proxy.sh

# PATH
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="$HOME/.homebrew/bin:$PATH"
export PATH="$HOME/.homebrew/sbin:$PATH"

# setup
os="$(uname -s)"
if [[ "$os" == MSYS* ]]; then
    export HOME=/c/Users/$(whoami)
    export WORKDIR=/home/$(whoami)
    export ZSH_PLUGIN=$HOME/.zsh
    alias open="explorer.exe"
elif [[ "$os" == Darwin ]]; then
    export WORKDIR=$HOME/work
    export ZSH_PLUGIN=$(brew --prefix)/share
elif [[ "$os" == Linux ]]; then
    export WORKDIR=$HOME/work
    export ZSH_PLUGIN=$(brew --prefix)/share
fi

# settings
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CONFIG_HOME=$HOME/.config
export PKG_CONFIG_PATH="$ZEROBREW_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
export ZSH_AUTO=$ZSH_PLUGIN/zsh-autosuggestions/zsh-autosuggestions.zsh
export ZSH_SYNTAX=$ZSH_PLUGIN/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_AUTOPAIR=$ZSH_PLUGIN/zsh-autopair/autopair.zsh
export ZSH_HIST_SEARCH=$ZSH_PLUGIN/zsh-history-substring-search/zsh-history-substring-search.zsh
export ZSH_CMP=$ZSH_PLUGIN/zsh-completions
export EDITOR=nvim
export COLORTERM=truecolor
export APPLE_SSH_ADD_BEHAVIOR=macos
export LESSHISTFILE=$XDG_STATE_HOME/lesshst
export HISTFILE=$XDG_STATE_HOME/zsh_history
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml
export MPLCONFIGDIR=$XDG_CACHE_HOME/matplotlib
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/node_js/npmrc
export IPYTHONDIR=$XDG_CACHE_HOME/ipython
export GIT_SSH_COMMAND="$(command -v ssh) -F $HOME/.ssh/config"
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=false
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=false
export PYTHONWARNINGS="ignore::UserWarning:IPython.core.interactiveshell"
if [ ! -e "$HISTFILE" ]; then mkdir -p "$(dirname "$HISTFILE")" && touch "$HISTFILE"; fi
if [ -e "$ZSH_AUTO" ]; then source $ZSH_AUTO; else echo "zsh-autosuggestions not found"; fi
if [ -e "$ZSH_AUTOPAIR" ]; then source $ZSH_AUTOPAIR; else echo "zsh-autopair not found"; fi
if [ -e "$ZSH_CMP" ]; then fpath=($ZSH_CMP $fpath); else echo "zsh-completions not found"; fi
if [ -e "$ZSH_SYNTAX" ]; then source $ZSH_SYNTAX; else echo "zsh-syntax-highlighting not found"; fi
if [[ -e "$ZSH_HIST_SEARCH" ]]; then
    source "$ZSH_HIST_SEARCH"
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
else
    echo "zsh-history-substring-search not found: $ZSH_HIST_SEARCH"
fi

# options
HISTSIZE=100000
SAVEHIST=100000
autoload -Uz compinit && compinit
autoload -Uz add-zsh-hook
setopt prompt_subst
setopt +o nonomatch
setopt share_history
setopt append_history
setopt auto_param_slash
setopt mark_dirs
setopt interactive_comments
setopt magic_equal_subst
setopt complete_in_word
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_no_store
blank_line_before_command_output() { print }
add-zsh-hook preexec blank_line_before_command_output
cd $WORKDIR

# git
alias gs="git status -s --ignored"
alias gp="git pull"
alias ga="git add"
alias gf="git push"
alias gS="git stash push"
alias gc="git commit -v -t ~/.config/git/commit"
alias go="git checkout"
alias gb="git branch"
alias gd="git diff"
alias gl="git log"
alias lg="lazygit"
alias gt="ga -A && gc -v -t ~/.config/git/commit && gp && gf"

# alias
alias c="clear"
alias cdr="cd $WORKDIR"
alias diff="delta"
alias mv="mv -i"
alias cp="cp -i -r"
alias grep="grep --color=auto -d skip"
alias iverilog="iverilog -g2012"
alias nvidia-smi="watch -n 1 nvidia-smi"
alias pin="uv pip install"
alias bb="brew bundle -vvv --file $HOME/.config/homebrew/Brewfile && brew upgrade"
alias bbc="brew bundle cleanup -f --file $XDG_CONFIG_HOME/homebrew/Brewfile && brew cleanup"
alias checkpy="pyright . && ruff format . && isort . --profile=black --gitignore && flake8 **/*.py --max-line-length=88; mypy . --disallow-untyped-defs --disable-error-code=import-not-found --exclude _marimo"
alias reset="cd $HOME/dotfiles && gp && cd $HOME/.ssh && gp && cd $HOME && command rm -rf $HOME/.cache $HOME/.config $HOME/.local && ~/dotfiles/setup.sh"
alias c-build="cmake -S . -B .build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja && ln -sf .build/compile_commands.json compile_commands.json"
if hash starship 2>/dev/null; then eval "$(starship init zsh)"; else echo "starship not found"; fi
if hash direnv 2>/dev/null; then eval "$(direnv hook zsh)"; else echo "direnv not found"; fi
if hash eza 2>/dev/null; then alias ls="eza -g --icons --sort Name"; else echo "eza not found"; fi
if hash eza 2>/dev/null; then alias la="eza -a -g --icons --sort Name"; else alias la="ls -a"; fi
if hash eza 2>/dev/null; then alias ll="eza -l -a -g --icons --sort Name"; else alias ll="ls -la"; fi
if hash eza 2>/dev/null; then alias lt="eza -T --git-ignore --sort Name"; fi
if hash bat 2>/dev/null; then alias cat="bat -p --paging=never --theme 'Visual Studio Dark+'"; else echo "bat not found"; fi
if hash htop 2>/dev/null; then alias top="htop"; else echo "htop not found"; fi
if hash nvim 2>/dev/null; then alias vim="nvim -O"; else echo "nvim not found"; fi
if hash rip 2>/dev/null; then alias rm="rip"; else echo "rip2 not found"; fi
if hash watchexec 2>/dev/null; then alias cdev="watchexec -e c,h,cpp,hpp cmake --build .build -j 16"; fi
if hash uv 2>/dev/null; then venv(){ uv venv .venv --python ${1:+$1} && printf '%s\n' 'source .venv/bin/activate' > .envrc && direnv allow .}; fi
if hash ipython 2>/dev/null; then python(){ [ "$#" -eq 0 ] && ipython || command python "$@"; }; fi
if hash pbcopy >/dev/null 2>&1 || hash xclip >/dev/null 2>&1 || hash clip >/dev/null 2>&1; then else echo "not found"; fi
