#!/usr/bin/env ruby

brew "bat"
brew "cmake"
brew "direnv"
brew "eza"
brew "git-delta"
brew "htop"
brew "lazygit"
brew "marp-cli"
brew "mas"
brew "neovim"
brew "node"
brew "ollama"
brew "podman"
brew "rip2"
brew "starship"
brew "tree-sitter-cli"
brew "uv"
brew "watch"
brew "zerobrewhq/zerobrew/zerobrew"
brew "zsh"
brew "zsh-autopair"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# python
brew "flake8"
brew "ipython"
brew "isort"
brew "pyright"
brew "ruff"

# cpp
brew "ninja"
brew "clang-format"
brew "llvm"

# lua
brew "stylua"
brew "lua-language-server"

# text
brew "prettier"
brew "latexindent"
