#!/usr/bin/env ruby

brew "bat"
brew "cmake"
brew "direnv"
brew "eza"
brew "git-delta"
brew "htop"
brew "lazygit"
brew "neovim"
brew "node"
brew "rip2"
brew "starship"
brew "tree-sitter-cli"
brew "zsh"
brew "zsh-autopair"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
cask "google-japanese-ime"
cask "font-hackgen-nerd"

if OS.mac?
  tap "0oastro/tap"
  brew "marp-cli"
  brew "mas"
  brew "watch"
  cask "0oastro/tap/raycast@beta"
  cask "box-drive"
  cask "chatgpt"
  cask "google-chrome"
  cask "microsoft-powerpoint"
  cask "0oastro/tap/raycast@beta", trusted: true
  cask "spotify"
  cask "wezterm@nightly"
  mas "Ethernet Menubar", id: 1549412235
  mas "Pure Paste", id: 1611378436
  mas "Xcode", id: 497799835
elsif OS.linux?
  cask "codex"
end

# python
brew "ipython"
brew "pyright"
brew "ruff"
brew "isort"
brew "flake8"

# cpp
brew "llvm"

# lua
brew "stylua"
brew "lua-language-server"

# markdown
brew "prettier"
