#!/usr/bin/env ruby

brew "bat"
brew "cmake"
brew "direnv"
brew "eza"
brew "git-delta"
brew "htop"
brew "lazygit"
brew "neovim"
brew "node"
brew "pkg-config"
brew "rip2"
brew "starship"
brew "tree-sitter-cli"
brew "zsh"
brew "zsh-autopair"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "font-hackgen-nerd"

if OS.mac?
tap "0oastro/tap"
brew "marp-cli"
brew "mas"
cask "0oastro/tap/raycast@beta"
cask "box-drive"
cask "cmd-eikana"
cask "docker-desktop"
cask "google-chrome"
cask "microsoft-powerpoint"
cask "0oastro/tap/raycast@beta"
cask "spotify"
cask "wezterm@nightly"
mas "Ethernet Menubar", id: 1549412235
mas "Pure Paste", id: 1611378436
mas "Xcode", id: 497799835
elsif OS.linux?
end

# python
brew "ipython"
brew "pyright"
brew "ruff"
brew "isort"
brew "flake8"

# lua
brew "stylua"
brew "lua-language-server"

# markdown
brew "prettier"
