#!/usr/bin/env ruby

cask "alt-tab"
cask "box-drive"
cask "font-hackgen-nerd"
cask "font-symbols-only-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "libreoffice"
cask "raycast"
cask "spotify"
cask "wezterm@nightly"
mas "Ethernet Menubar", id: 1549412235
mas "Pure Paste", id: 1611378436
mas "Xcode", id: 497799835
