#!/bin/bash

IFS=$'\n'

if [ "$1 " = "size " ]; then
    objects=$(git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head)
    echo "All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file."
    output="size,pack,SHA,location"
    for y in $objects; do
        size=$(($(echo "$y" | cut -f 5 -d ' ') / 1024))
        compressedSize=$(($(echo "$y" | cut -f 6 -d ' ') / 1024))
        sha=$(echo "$y" | cut -f 1 -d ' ')
        other=$(git rev-list --all --objects | grep "$sha")
        output="${output}\n${size},${compressedSize},${other}"
    done
    echo -e "$output" | column -t -s ', '
else
    git "$@"
fi
