#!/usr/bin/env python3

import os
import ssl
import sys
from socket import gethostname

try:
    import slackweb
except ImportError:
    os.system("pip3 install -U pip")
    os.system("pip3 install slackweb")
    import slackweb

ssl._create_default_https_context = ssl._create_unverified_context
slack = slackweb.Slack(
    url="https://hooks.slack.com/services/"
    + "T038Q34FPQV/B038T03FSF4/SLNY49UsE6QKHMbp1t2ee0YC"
)
comment = sys.argv[1] if len(sys.argv) > 1 else ""
slack.notify(text=f"{gethostname()} で計算が終了しました\n{comment}")
