#!/usr/bin/env python

import os
import subprocess
import sys

try:
    import nbformat
except ImportError:
    print("install notebook")
    os.system("pip install notebook -q")
    import nbformat

try:
    import black
except ImportError:
    print("install black")
    os.system("pip install black -q")

try:
    import isort
except ImportError:
    print("install isort")
    os.system("pip install isort -q")

__all__ = ["black", "isort"]
filename = sys.argv[1]
base_name, extension = os.path.splitext(filename)
if extension == ".ipynb":
    subprocess.run(["jupyter", "nbconvert", "--to", "python", filename])
    subprocess.run(["black", base_name + ".py", "-q"])
    subprocess.run(["isort", base_name + ".py", "-q"])

elif extension == ".py":
    nb = nbformat.v4.new_notebook()
    nb["cells"] = []
    input = open(filename)
    next(next(input))
    for line in input:
        if line != "\n":
            if line.startswith("# In["):
                nb["cells"].append(nbformat.v4.new_code_cell(""))
            elif nb["cells"] != []:
                nb["cells"][-1]["source"] += line
    nbformat.write(nb, open(base_name + ".ipynb", "w"))

else:
    raise ValueError("Unknown file type")
