view:
	(open http://localhost:8080/_marp.md) & marp -s . --html --theme ntt.css

html:
	exec marp _marp.md --html --theme ntt.css --allow-local-files

pptx:
	exec marp _marp.md --html --theme ntt.css --pptx --allow-local-files

pdf:
	exec marp _marp.md --html --theme ntt.css --pdf --allow-local-files
